// Auto-generated from "Tracklynk Lite Feature set.xlsx" + CODE AUDIT of the
// prototype at apps/Final-Prototype/tl-lite-progressive-web-app (audited 2026-06-10).
// Bouncie vs. Tracklynk Lite head-to-head (Vyncs omitted).
// inBouncie  = presence per the spreadsheet's Bouncie column ('yes'|'no'|'partial').
// inTracklynk = CODE-VERIFIED presence in the prototype ('yes'|'partial'|'no').
//   tlEvidence = source file (relative to src/) backing that verdict; tlNote = why.
// scope = 'v1' (committed) | 'v2' (roadmap) | 'other' (competitive context) — from the spec sheets.
// bouncie / tracklynk text fields remain the spreadsheet's descriptive spec.

export const COMPARISON = [
  {
    "category": "GPS & Location Tracking",
    "rows": [
      {
        "feature": "Real-Time GPS Tracking",
        "segment": "B2C/B2B",
        "bouncie": "Yes. 4G LTE-M cellular with ~15-second continuous streaming.",
        "tracklynk": "Yes. ~10-sec or real-time continuous streaming. Highest refresh rate in class - included in base plan.",
        "status": "working",
        "statusLabel": "Working",
        "tag": "Shared",
        "inBouncie": "yes",
        "inTracklynk": "yes",
        "scope": "v1",
        "tlEvidence": "pages/home/index.tsx",
        "tlNote": "live Google map with vehicle puck"
      },
      {
        "feature": "GPS Update Frequency",
        "segment": "B2C/B2B",
        "bouncie": "~15 seconds (recent upgrade got real-time continuous streaming).",
        "tracklynk": "~10 sec or real-time continuous streaming. Highest refresh rate in class.",
        "status": "issues",
        "statusLabel": "Issues",
        "tag": "Shared",
        "inBouncie": "yes",
        "inTracklynk": "partial",
        "scope": "v1",
        "tlEvidence": "contexts/LiveTelemetryContext.tsx",
        "tlNote": "telemetry refresh exists, no frequency setting"
      },
      {
        "feature": "Engine-Off Location Pings",
        "segment": "B2C/B2B",
        "bouncie": "No. Device enters low-power sleep mode; tracking ceases when ignition is off.",
        "tracklynk": "Yes. Low-power GPS pings every 30 min while parked. Balances battery drain and theft visibility.",
        "status": "working",
        "statusLabel": "Working",
        "tag": "TL adds (Bouncie gap)",
        "inBouncie": "no",
        "inTracklynk": "partial",
        "scope": "v1",
        "tlEvidence": "pages/home/index.tsx",
        "tlNote": "parked state shown, no ping-interval feature"
      },
      {
        "feature": "Trip History Logging",
        "segment": "B2C/B2B",
        "bouncie": "Unlimited retention. Exclusive \"Day View\" aggregates all daily stops.",
        "tracklynk": "Unlimited retention with Day View + weekly/monthly trip summaries auto-generated. Exportable logs.",
        "status": "working",
        "statusLabel": "Working",
        "tag": "Shared",
        "inBouncie": "yes",
        "inTracklynk": "yes",
        "scope": "v1",
        "tlEvidence": "pages/trips/index.tsx",
        "tlNote": "trip list backed by trips.ts"
      },
      {
        "feature": "Day View - All Trips on One Canvas",
        "segment": "B2C",
        "bouncie": "Yes. Introduced v4.15.x (Sept 2025). All trips for selected day overlaid on one map.",
        "tracklynk": "Yes. Included with weekly/monthly summaries.",
        "status": "working",
        "statusLabel": "Working",
        "tag": "Bouncie-origin · TL adopts",
        "inBouncie": "yes",
        "inTracklynk": "yes",
        "scope": "v1",
        "tlEvidence": "pages/trips/day/index.tsx",
        "tlNote": "dedicated day-view route"
      },
      {
        "feature": "Route Replay Visualization",
        "segment": "B2C/B2B",
        "bouncie": "Continuous breadcrumb trail with color-coded speed bands (green/yellow/red by speed vs. posted limits).",
        "tracklynk": "Continuous breadcrumb trail with color-coded speed bands + animated trip replay with play/pause/speed controls.",
        "status": "conditional",
        "statusLabel": "Conditional",
        "tag": "Shared",
        "inBouncie": "yes",
        "inTracklynk": "yes",
        "scope": "v1",
        "tlEvidence": "pages/trips/detail/index.tsx",
        "tlNote": "animated playback with speed-band coloring"
      },
      {
        "feature": "Geofencing Geometry",
        "segment": "B2C/B2B",
        "bouncie": "Circular radial zones only. Pinch to resize.",
        "tracklynk": "Both circular zones AND custom polygon geofences.",
        "status": "working",
        "statusLabel": "Working",
        "tag": "TL exceeds Bouncie",
        "inBouncie": "yes",
        "inTracklynk": "partial",
        "scope": "v1",
        "tlEvidence": "pages/settings/alerts/geo-zone/create.tsx",
        "tlNote": "circle/radius only, no polygon"
      },
      {
        "feature": "Live Map Auto-Refresh",
        "segment": "B2C/B2B",
        "bouncie": "Included natively in base subscription.",
        "tracklynk": "Included natively in base subscription. No upsell required.",
        "status": "issues",
        "statusLabel": "Issues",
        "tag": "Bouncie strength",
        "inBouncie": "yes",
        "inTracklynk": "yes",
        "scope": "v1",
        "tlEvidence": "contexts/LiveTelemetryContext.tsx",
        "tlNote": "telemetry-driven live marker updates"
      },
      {
        "feature": "Geographic Coverage",
        "segment": "B2C/B2B",
        "bouncie": "United States, Canada, and Mexico only (AT&T + T-Mobile networks).",
        "tracklynk": "US, Canada, and Mexico (multi-carrier: AT&T, T-Mobile, Verizon fallback).",
        "status": "working",
        "statusLabel": "Working",
        "tag": "TL adds (Bouncie gap)",
        "inBouncie": "yes",
        "inTracklynk": "no",
        "scope": "v1",
        "tlEvidence": "",
        "tlNote": "network/coverage is hardware, not coded"
      },
      {
        "feature": "Current Location Pin",
        "segment": "B2C/B2B",
        "bouncie": "Yes. Exact parked address updated on each engine-off event.",
        "tracklynk": "Yes. Exact address with engine-off and periodic ping updates.",
        "status": "working",
        "statusLabel": "Working",
        "tag": "Shared",
        "inBouncie": "yes",
        "inTracklynk": "yes",
        "scope": "other",
        "tlEvidence": "pages/home/index.tsx",
        "tlNote": "live vehicle marker on map"
      },
      {
        "feature": "Real-Time Traffic Overlay",
        "segment": "B2C/B2B",
        "bouncie": "Yes. Added in v4.14+. Google Maps traffic layer.",
        "tracklynk": "Yes. Google Maps traffic layer included.",
        "status": "working",
        "statusLabel": "Working",
        "tag": "Shared",
        "inBouncie": "yes",
        "inTracklynk": "yes",
        "scope": "other",
        "tlEvidence": "pages/home/index.tsx",
        "tlNote": "Google TrafficLayer toggle"
      },
      {
        "feature": "Map Provider",
        "segment": "B2C/B2B",
        "bouncie": "Google Maps (confirmed via @agm/core Angular Maps library + @mapbox/polyline).",
        "tracklynk": "Google Maps.",
        "status": "working",
        "statusLabel": "Working",
        "tag": "Shared",
        "inBouncie": "yes",
        "inTracklynk": "yes",
        "scope": "other",
        "tlEvidence": "pages/home/index.tsx",
        "tlNote": "Google Maps via react-google-maps"
      }
    ]
  },
  {
    "category": "OBD & Vehicle Diagnostics",
    "rows": [
      {
        "feature": "DTC Fault Code Reading",
        "segment": "B2C/B2B",
        "bouncie": "Yes. Reads and decodes Diagnostic Trouble Codes in plain English.",
        "tracklynk": "Yes. Reads, decodes, and categorizes DTCs by severity (Critical / Warning / Informational) with suggested actions.",
        "status": "working",
        "statusLabel": "Working",
        "tag": "Shared",
        "inBouncie": "yes",
        "inTracklynk": "yes",
        "scope": "v1",
        "tlEvidence": "pages/vehicles/health/engine/index.tsx",
        "tlNote": "DTC cards from vehicleHealth.ts"
      },
      {
        "feature": "Check Engine Light Alerts",
        "segment": "B2C/B2B",
        "bouncie": "Yes. Instant push notifications with plain-language decoding.",
        "tracklynk": "Yes. Instant push + in-app alert with plain-language decoding and severity rating. Option to auto-share with mechanic.",
        "status": "working",
        "statusLabel": "Working",
        "tag": "Shared",
        "inBouncie": "yes",
        "inTracklynk": "yes",
        "scope": "v1",
        "tlEvidence": "pages/settings/alerts/index.tsx",
        "tlNote": "DTC/check-engine alert config"
      },
      {
        "feature": "Battery Health Monitoring",
        "segment": "B2C/B2B",
        "bouncie": "Binary indicator (Good/Bad) based on broad voltage thresholds.",
        "tracklynk": "Granular voltage-level monitoring with trend graph. Alert triggers at user-defined voltage thresholds (e.g., <12.2V).",
        "status": "issues",
        "statusLabel": "Issues",
        "tag": "TL exceeds Bouncie",
        "inBouncie": "partial",
        "inTracklynk": "yes",
        "scope": "v1",
        "tlEvidence": "pages/vehicles/health/battery/index.tsx",
        "tlNote": "voltage gauge plus trend chart"
      },
      {
        "feature": "Fuel Level Display",
        "segment": "B2C/B2B",
        "bouncie": "Supported on compatible vehicles. Shows percentage only.",
        "tracklynk": "Supported on compatible vehicles with fill-up detection and cost-per-mile calculation.",
        "status": "conditional",
        "statusLabel": "Conditional",
        "tag": "TL exceeds Bouncie",
        "inBouncie": "yes",
        "inTracklynk": "yes",
        "scope": "v1",
        "tlEvidence": "pages/vehicles/health/fuel/index.tsx",
        "tlNote": "fuel dial and detail page"
      },
      {
        "feature": "Maintenance Reminders / Scheduler",
        "segment": "B2C/B2B",
        "bouncie": "Full Care Plan: oil, tires, wipers, fluids, registration, emissions + custom tasks. Mileage or date triggers.",
        "tracklynk": "Smart mileage/time reminders with custom task creation. Users add any service type with custom intervals.",
        "status": "working",
        "statusLabel": "Working",
        "tag": "Bouncie strength",
        "inBouncie": "yes",
        "inTracklynk": "yes",
        "scope": "v1",
        "tlEvidence": "pages/vehicles/health/maintenance/index.tsx",
        "tlNote": "service schedule with due reminders"
      },
      {
        "feature": "Manufacturer Recall Alerts",
        "segment": "B2C/B2B",
        "bouncie": "Not supported.",
        "tracklynk": "Yes. VIN-based recall alerts sourced from NHTSA database with direct links to schedule service.",
        "status": "working",
        "statusLabel": "Working",
        "tag": "TL adds (Bouncie gap)",
        "inBouncie": "no",
        "inTracklynk": "yes",
        "scope": "v1",
        "tlEvidence": "pages/vehicles/health/recalls/index.tsx",
        "tlNote": "NHTSA recall list page"
      },
      {
        "feature": "Emission Score / Test Prediction",
        "segment": "B2C",
        "bouncie": "Not supported.",
        "tracklynk": "Not supported. (Low user demand; keeps UX simple.)",
        "status": "working",
        "statusLabel": "Working",
        "tag": "TL adds (Bouncie gap)",
        "inBouncie": "no",
        "inTracklynk": "partial",
        "scope": "v1",
        "tlEvidence": "data/vehicleHealth.ts",
        "tlNote": "emissions mentioned in DTC desc only"
      },
      {
        "feature": "Engine RPM Monitoring",
        "segment": "B2C",
        "bouncie": "Not surfaced to users.",
        "tracklynk": "Not supported.",
        "status": "working",
        "statusLabel": "Working",
        "tag": "TL adds (Bouncie gap)",
        "inBouncie": "no",
        "inTracklynk": "partial",
        "scope": "other",
        "tlEvidence": "pages/settings/alerts/ConfigSheets.tsx",
        "tlNote": "RPM only in idle-detection config copy"
      },
      {
        "feature": "True OBD Idle Detection",
        "segment": "B2C/B2B",
        "bouncie": "Basic idle tracking - GPS-based estimate (stationary for 5+ minutes).",
        "tracklynk": "True idle detection (RPM > 0, speed = 0) with customizable idle duration alerts (e.g., 3 min, 5 min, 10 min).",
        "status": "working",
        "statusLabel": "Working",
        "tag": "TL adds (Bouncie gap)",
        "inBouncie": "partial",
        "inTracklynk": "yes",
        "scope": "v1",
        "tlEvidence": "pages/settings/alerts/ConfigSheets.tsx",
        "tlNote": "RPM+speed idle detection mode selector"
      },
      {
        "feature": "Gas Station Fuel Economy Comparison",
        "segment": "B2C",
        "bouncie": "Not supported.",
        "tracklynk": "Not supported. (Avoids UX bloat.)",
        "status": "working",
        "statusLabel": "Working",
        "tag": "TL adds (Bouncie gap)",
        "inBouncie": "no",
        "inTracklynk": "no",
        "scope": "other",
        "tlEvidence": "",
        "tlNote": "no gas-station price comparison present"
      },
      {
        "feature": "Fuel Economy (MPG) Reporting",
        "segment": "B2C/B2B",
        "bouncie": "Per-trip MPG using distance + OBD fuel data.",
        "tracklynk": "Fuel economy scoring per trip with weekly efficiency trends. No gas-station comparison.",
        "status": "working",
        "statusLabel": "Working",
        "tag": "Shared",
        "inBouncie": "yes",
        "inTracklynk": "yes",
        "scope": "v1",
        "tlEvidence": "pages/vehicles/health/fuel/index.tsx",
        "tlNote": "avg MPG and per-trip MPG"
      },
      {
        "feature": "Recall Database Background Check",
        "segment": "B2C/B2B",
        "bouncie": "Not supported.",
        "tracklynk": "Yes. Background VIN monitoring with automatic alerts.",
        "status": "working",
        "statusLabel": "Working",
        "tag": "TL adds (Bouncie gap)",
        "inBouncie": "no",
        "inTracklynk": "yes",
        "scope": "v1",
        "tlEvidence": "pages/vehicles/health/recalls/index.tsx",
        "tlNote": "VIN recall checking screen"
      },
      {
        "feature": "OBD Data Accuracy",
        "segment": "B2C/B2B",
        "bouncie": "Compatible vehicles. Not all PIDs available on all makes.",
        "tracklynk": "Compatible vehicles. Validated against known PID support tables per make/model.",
        "status": "issues",
        "statusLabel": "Issues",
        "tag": "Shared",
        "inBouncie": "yes",
        "inTracklynk": "no",
        "scope": "other",
        "tlEvidence": "",
        "tlNote": "hardware quality claim, not coded"
      },
      {
        "feature": "OBD Port Compatibility",
        "segment": "B2C/B2B",
        "bouncie": "OBD-II 1996+ vehicles. No J1939 (heavy-duty).",
        "tracklynk": "OBD-II 1996+ vehicles. No J1939.",
        "status": "working",
        "statusLabel": "Working",
        "tag": "Shared",
        "inBouncie": "yes",
        "inTracklynk": "partial",
        "scope": "other",
        "tlEvidence": "pages/settings/support/index.tsx",
        "tlNote": "OBD-II compatibility only in FAQ copy"
      }
    ]
  },
  {
    "category": "Driver Behaviour Monitoring",
    "rows": [
      {
        "feature": "Speeding Detection & Alerts",
        "segment": "B2C/B2B",
        "bouncie": "Yes. Maps speeds against posted speed limits + custom thresholds.",
        "tracklynk": "Yes. Posted limits + custom thresholds per geofence zone (e.g., 25 mph school zone). Alert modes: Push, SMS, or Silent Log.",
        "status": "working",
        "statusLabel": "Working",
        "tag": "Shared",
        "inBouncie": "yes",
        "inTracklynk": "yes",
        "scope": "v1",
        "tlEvidence": "data/driverFactors.ts",
        "tlNote": "speed factor and alert config"
      },
      {
        "feature": "Hard Braking Detection",
        "segment": "B2C/B2B",
        "bouncie": "Yes. 3 sensitivity levels (Light / Moderate / Excessive). Adjustable per driver context.",
        "tracklynk": "Yes. 3-axis accelerometer with adjustable sensitivity. Separate configurable thresholds for acceleration vs. braking.",
        "status": "working",
        "statusLabel": "Working",
        "tag": "Shared",
        "inBouncie": "yes",
        "inTracklynk": "yes",
        "scope": "v1",
        "tlEvidence": "data/driverFactors.ts",
        "tlNote": "hard-braking factor and alert"
      },
      {
        "feature": "Rapid Acceleration Detection",
        "segment": "B2C/B2B",
        "bouncie": "Yes. 3 sensitivity levels (Light / Moderate / Excessive).",
        "tracklynk": "Yes. Adjustable sensitivity. Separate thresholds for acceleration vs. braking.",
        "status": "working",
        "statusLabel": "Working",
        "tag": "Shared",
        "inBouncie": "yes",
        "inTracklynk": "yes",
        "scope": "v1",
        "tlEvidence": "data/driverFactors.ts",
        "tlNote": "rapid-accel factor and alert"
      },
      {
        "feature": "Rough Cornering Detection",
        "segment": "B2B",
        "bouncie": "Not supported.",
        "tracklynk": "Yes. Lateral G-force monitoring with adjustable trigger sensitivity. Logged per trip for scoring.",
        "status": "working",
        "statusLabel": "Working",
        "tag": "TL adds (Bouncie gap)",
        "inBouncie": "no",
        "inTracklynk": "yes",
        "scope": "v1",
        "tlEvidence": "data/driverFactors.ts",
        "tlNote": "cornering factor and alert"
      },
      {
        "feature": "Driver Safety Score",
        "segment": "B2C/B2B",
        "bouncie": "Yes. Composite ring gauge (0–100) per trip in Driving Insights screen.",
        "tracklynk": "Yes. Composite score per trip + rolling 7-day and 30-day driver profile. Score breakdown by category.",
        "status": "working",
        "statusLabel": "Working",
        "tag": "Shared",
        "inBouncie": "yes",
        "inTracklynk": "yes",
        "scope": "v1",
        "tlEvidence": "pages/health/index.tsx",
        "tlNote": "driver health score with factor breakdown"
      },
      {
        "feature": "Driver Score Tournaments / Gamification",
        "segment": "B2C",
        "bouncie": "Not supported.",
        "tracklynk": "Yes. Family leaderboard with weekly rankings. No community-wide benchmarking (privacy-first approach).",
        "status": "working",
        "statusLabel": "Working",
        "tag": "TL adds (Bouncie gap)",
        "inBouncie": "no",
        "inTracklynk": "yes",
        "scope": "v1",
        "tlEvidence": "pages/health/leaderboard/index.tsx",
        "tlNote": "podium/ranking leaderboard"
      },
      {
        "feature": "Idle Time Tracking",
        "segment": "B2C/B2B",
        "bouncie": "Basic - GPS-based estimate (stationary for 5+ minutes).",
        "tracklynk": "True idle detection (RPM > 0, speed = 0) with customizable idle duration alerts.",
        "status": "conditional",
        "statusLabel": "Conditional",
        "tag": "TL exceeds Bouncie",
        "inBouncie": "partial",
        "inTracklynk": "yes",
        "scope": "v1",
        "tlEvidence": "data/trips.ts",
        "tlNote": "idleMins per trip plus idle alerts"
      },
      {
        "feature": "Per-Trip Driving Report",
        "segment": "B2C/B2B",
        "bouncie": "Yes. Full breakdown: braking count, acceleration events, max speed, avg speed, idle, fuel, efficiency %.",
        "tracklynk": "Yes. Full breakdown + safety score by category + fuel cost per trip.",
        "status": "working",
        "statusLabel": "Working",
        "tag": "Shared",
        "inBouncie": "yes",
        "inTracklynk": "yes",
        "scope": "v1",
        "tlEvidence": "pages/trips/detail/index.tsx",
        "tlNote": "per-trip score, events, speed chart"
      },
      {
        "feature": "Insurance Telematics (UBI)",
        "segment": "B2C",
        "bouncie": "Not supported.",
        "tracklynk": "Not supported. (Planned for future integration.)",
        "status": "working",
        "statusLabel": "Working",
        "tag": "TL adds (Bouncie gap)",
        "inBouncie": "no",
        "inTracklynk": "yes",
        "scope": "v2",
        "tlEvidence": "pages/settings/insurance/index.tsx",
        "tlNote": "UBI opt-in, carriers, score card"
      },
      {
        "feature": "Curfew / Hours of Operation",
        "segment": "B2C/B2B",
        "bouncie": "Yes. Alerts if vehicle moves outside permitted hours.",
        "tracklynk": "Yes. Multi-schedule curfew windows (weekday vs. weekend). Alerts on both start and end of movement.",
        "status": "working",
        "statusLabel": "Working",
        "tag": "Shared",
        "inBouncie": "yes",
        "inTracklynk": "yes",
        "scope": "v1",
        "tlEvidence": "pages/settings/alerts/curfew/index.tsx",
        "tlNote": "curfew time-window config page"
      }
    ]
  },
  {
    "category": "Safety & Security",
    "rows": [
      {
        "feature": "Accident / Impact Detection",
        "segment": "B2C",
        "bouncie": "Yes. Full-screen modal + auto-SMS to contacts + Call 911 CTA.",
        "tracklynk": "Yes. High-G detection triggers: push, SMS to 5 contacts, optional auto-call to emergency contact.",
        "status": "issues",
        "statusLabel": "Issues",
        "tag": "Shared",
        "inBouncie": "yes",
        "inTracklynk": "yes",
        "scope": "v1",
        "tlEvidence": "pages/settings/safety/impact/index.tsx",
        "tlNote": "impact detection config and events"
      },
      {
        "feature": "Emergency Contact Auto-SMS",
        "segment": "B2C",
        "bouncie": "Yes. Auto-sends SMS to designated contacts on crash detection.",
        "tracklynk": "Yes. Automatic SMS to up to 5 emergency contacts + optional auto-call.",
        "status": "issues",
        "statusLabel": "Issues",
        "tag": "Bouncie-origin · TL adopts",
        "inBouncie": "yes",
        "inTracklynk": "yes",
        "scope": "v1",
        "tlEvidence": "pages/settings/safety/impact/index.tsx",
        "tlNote": "SMS to emergency contacts toggle"
      },
      {
        "feature": "SOS / Emergency Alerts",
        "segment": "B2C",
        "bouncie": "Auto crash SMS + optional Call 911 in-app CTA.",
        "tracklynk": "Auto crash SMS + Call 911 + optional auto-call to first emergency contact.",
        "status": "working",
        "statusLabel": "Working",
        "tag": "Shared",
        "inBouncie": "yes",
        "inTracklynk": "yes",
        "scope": "v1",
        "tlEvidence": "pages/settings/safety/impact/index.tsx",
        "tlNote": "auto-call/SMS emergency contacts"
      },
      {
        "feature": "Towing Alert (Engine-Off Movement)",
        "segment": "B2C/B2B",
        "bouncie": "Not supported. Cannot detect - no tracking when engine off.",
        "tracklynk": "Yes. Movement without ignition detection triggers multi-channel alert.",
        "status": "working",
        "statusLabel": "Working",
        "tag": "TL adds (Bouncie gap)",
        "inBouncie": "no",
        "inTracklynk": "yes",
        "scope": "v1",
        "tlEvidence": "pages/settings/safety/theft/index.tsx",
        "tlNote": "tow-detection toggle in theft mode"
      },
      {
        "feature": "Tamper / Device Removal Alert",
        "segment": "B2C/B2B",
        "bouncie": "Yes. Alerts on physical removal from OBD port.",
        "tracklynk": "Yes. Instant multi-channel alert (push + SMS) with last-known GPS coordinates at time of unplug.",
        "status": "working",
        "statusLabel": "Working",
        "tag": "Shared",
        "inBouncie": "yes",
        "inTracklynk": "yes",
        "scope": "v1",
        "tlEvidence": "pages/settings/safety/tamper/index.tsx",
        "tlNote": "OBD disconnect/tamper detection page"
      },
      {
        "feature": "Roadside Assistance",
        "segment": "B2C",
        "bouncie": "Included in ALL plans. 3 free claims/year (towing, jumpstart, flat tire, fuel, lockout).",
        "tracklynk": "Included in base subscription. 3 claims/year (towing up to 25 mi, jump-start, fuel delivery, lockout). No per-claim cap.",
        "status": "conditional",
        "statusLabel": "Conditional",
        "tag": "Bouncie strength",
        "inBouncie": "yes",
        "inTracklynk": "yes",
        "scope": "v1",
        "tlEvidence": "pages/settings/safety/roadside/index.tsx",
        "tlNote": "request service and claims history"
      },
      {
        "feature": "Severe Weather Alerts",
        "segment": "B2C",
        "bouncie": "Yes. NWS severe weather advisories near vehicle location. Push notification sent.",
        "tracklynk": "Yes. NWS integration + custom weather-trigger alerts filterable by severity level.",
        "status": "working",
        "statusLabel": "Working",
        "tag": "Bouncie-origin · TL adopts",
        "inBouncie": "yes",
        "inTracklynk": "yes",
        "scope": "v1",
        "tlEvidence": "services/useNwsAlerts.ts",
        "tlNote": "NWS weather alerts and badge"
      },
      {
        "feature": "Unauthorized Movement Alert",
        "segment": "B2C/B2B",
        "bouncie": "Engine-on only. Detects unexpected engine start from parked position.",
        "tracklynk": "Both engine-on and engine-off movement detection with combined \"Theft Mode\" alert.",
        "status": "conditional",
        "statusLabel": "Conditional",
        "tag": "TL exceeds Bouncie",
        "inBouncie": "partial",
        "inTracklynk": "yes",
        "scope": "v1",
        "tlEvidence": "data/safety.ts",
        "tlNote": "geofence-breach/unauthorized-start theft events"
      },
      {
        "feature": "Anti-Theft / Stolen Vehicle Recovery",
        "segment": "B2C/B2B",
        "bouncie": "Limited. Relies on geofence breaches while engine is running. Loses location when engine off.",
        "tracklynk": "High. Engine-off GPS + geofence breach + towing detection. Combined \"Theft Mode\" activates all alerts simultaneously.",
        "status": "conditional",
        "statusLabel": "Conditional",
        "tag": "TL exceeds Bouncie",
        "inBouncie": "partial",
        "inTracklynk": "yes",
        "scope": "v1",
        "tlEvidence": "pages/settings/safety/theft/index.tsx",
        "tlNote": "theft arm modes and event history"
      },
      {
        "feature": "Lifetime Device Assurance",
        "segment": "B2C/B2B",
        "bouncie": "Not supported. 3G-to-4G transition bricked devices with no trade-in program.",
        "tracklynk": "Yes. Free device replacement while subscription is active.",
        "status": "working",
        "statusLabel": "Working",
        "tag": "TL adds (Bouncie gap)",
        "inBouncie": "no",
        "inTracklynk": "no",
        "scope": "other",
        "tlEvidence": "",
        "tlNote": "warranty policy, not a code feature"
      }
    ]
  },
  {
    "category": "Fleet Management & Commercial Operations",
    "rows": [
      {
        "feature": "Multi-Vehicle Account",
        "segment": "B2B",
        "bouncie": "Unlimited vehicles on all plans.",
        "tracklynk": "Unlimited vehicles on unified map. No per-vehicle caps.",
        "status": "conditional",
        "statusLabel": "Conditional",
        "tag": "Bouncie strength",
        "inBouncie": "yes",
        "inTracklynk": "yes",
        "scope": "v1",
        "tlEvidence": "contexts/VehicleContext.tsx",
        "tlNote": "multiple vehicles, switcher, fleet list"
      },
      {
        "feature": "Fleet Dashboard",
        "segment": "B2B",
        "bouncie": "All vehicles on one map in both mobile + web app. Seamless approach.",
        "tracklynk": "Unified map with all vehicles. Web + mobile parity.",
        "status": "working",
        "statusLabel": "Working",
        "tag": "Shared",
        "inBouncie": "yes",
        "inTracklynk": "yes",
        "scope": "v1",
        "tlEvidence": "pages/fleet/index.tsx",
        "tlNote": "fleet overview hub"
      },
      {
        "feature": "Driver Assignment",
        "segment": "B2B",
        "bouncie": "Yes. Single-driver-per-vehicle model.",
        "tracklynk": "Yes. Driver-per-vehicle with manager override capability.",
        "status": "working",
        "statusLabel": "Working",
        "tag": "Shared",
        "inBouncie": "yes",
        "inTracklynk": "yes",
        "scope": "v1",
        "tlEvidence": "pages/fleet/assignments/index.tsx",
        "tlNote": "vehicle to driver assignment list"
      },
      {
        "feature": "Role-Based Access Control",
        "segment": "B2B",
        "bouncie": "Field supervisors, dispatchers, team members. Granular access per team.",
        "tracklynk": "Admin / Manager / Viewer roles with customizable permissions per vehicle group.",
        "status": "working",
        "statusLabel": "Working",
        "tag": "Shared",
        "inBouncie": "yes",
        "inTracklynk": "yes",
        "scope": "v1",
        "tlEvidence": "data/fleetOps.ts",
        "tlNote": "admin/manager/viewer capability matrix"
      },
      {
        "feature": "Vehicle Grouping",
        "segment": "B2B",
        "bouncie": "Group by region or team.",
        "tracklynk": "Group by region, team, or custom tag. Drag-and-drop reorganization.",
        "status": "working",
        "statusLabel": "Working",
        "tag": "Shared",
        "inBouncie": "yes",
        "inTracklynk": "no",
        "scope": "v1",
        "tlEvidence": "",
        "tlNote": "no vehicle group/folder concept"
      },
      {
        "feature": "Data Export (CSV/Reports)",
        "segment": "B2B",
        "bouncie": "CSV export for trips + maintenance data.",
        "tracklynk": "CSV and Excel export for trips, maintenance, fuel, and driver scores. Pre-formatted tax/expense templates.",
        "status": "working",
        "statusLabel": "Working",
        "tag": "Shared",
        "inBouncie": "yes",
        "inTracklynk": "yes",
        "scope": "v1",
        "tlEvidence": "pages/trips/export/index.tsx",
        "tlNote": "PDF/CSV/QuickBooks export screen"
      },
      {
        "feature": "Dispatch Map with Custom Locations",
        "segment": "B2B",
        "bouncie": "Not supported natively; relies on third-party API integration.",
        "tracklynk": "Built-in dispatch pin-drop on map. Assign vehicles to stops and track arrival/departure with ETA.",
        "status": "working",
        "statusLabel": "Working",
        "tag": "TL adds (Bouncie gap)",
        "inBouncie": "no",
        "inTracklynk": "no",
        "scope": "v1",
        "tlEvidence": "",
        "tlNote": "no dispatch map or custom-location entities"
      },
      {
        "feature": "Stop Time Visualization",
        "segment": "B2B",
        "bouncie": "Basic trip end logging. Day View shows stop locations but not duration.",
        "tracklynk": "Precise stop duration with geo-tagged coordinates. Configurable minimum stop threshold (e.g., ignore < 2 min).",
        "status": "working",
        "statusLabel": "Working",
        "tag": "TL adds (Bouncie gap)",
        "inBouncie": "partial",
        "inTracklynk": "no",
        "scope": "v1",
        "tlEvidence": "",
        "tlNote": "no stop-duration visualization found"
      },
      {
        "feature": "Mileage Tracking & IRS Reporting",
        "segment": "B2B",
        "bouncie": "CSV export with mileage data for tax reporting.",
        "tracklynk": "Mileage tracking with personal/business trip categorization. Pre-formatted IRS reports.",
        "status": "working",
        "statusLabel": "Working",
        "tag": "TL exceeds Bouncie",
        "inBouncie": "yes",
        "inTracklynk": "yes",
        "scope": "other",
        "tlEvidence": "pages/trips/categorize/index.tsx",
        "tlNote": "IRS-deductible categories and mileage export"
      },
      {
        "feature": "Operating Hours / Curfew Enforcement",
        "segment": "B2B",
        "bouncie": "Yes. Alerts on after-hours vehicle use.",
        "tracklynk": "Yes. Multi-schedule windows (weekday vs. weekend). Alerts on both start and end of unauthorized movement.",
        "status": "working",
        "statusLabel": "Working",
        "tag": "Shared",
        "inBouncie": "yes",
        "inTracklynk": "yes",
        "scope": "v1",
        "tlEvidence": "pages/settings/alerts/curfew/index.tsx",
        "tlNote": "curfew config doubles as operating hours"
      },
      {
        "feature": "Web Portal Dashboard",
        "segment": "B2B",
        "bouncie": "Modern web portal at bouncie.app - mirrors mobile app.",
        "tracklynk": "Modern responsive web portal with full mobile parity.",
        "status": "working",
        "statusLabel": "Working",
        "tag": "Bouncie strength",
        "inBouncie": "yes",
        "inTracklynk": "no",
        "scope": "other",
        "tlEvidence": "",
        "tlNote": "this app is the mobile PWA only"
      },
      {
        "feature": "Fleet Cost Analysis",
        "segment": "B2B",
        "bouncie": "Trip data export enables cost analysis in external spreadsheets.",
        "tracklynk": "Per-vehicle and fleet-wide fuel spend dashboards. Auto-links to OBD fuel fill-up detection.",
        "status": "working",
        "statusLabel": "Working",
        "tag": "TL exceeds Bouncie",
        "inBouncie": "yes",
        "inTracklynk": "partial",
        "scope": "v1",
        "tlEvidence": "pages/vehicles/fuel/index.tsx",
        "tlNote": "fleet fuel spend, no broader cost analysis"
      },
      {
        "feature": "API Integration",
        "segment": "B2B",
        "bouncie": "Open REST API, Webhooks, OAuth 2.0. Public documentation at docs.bouncie.dev.",
        "tracklynk": "Open REST API with Webhooks and OAuth 2.0. Pre-built Google Sheets + Zapier integrations. No enterprise gate.",
        "status": "working",
        "statusLabel": "Working",
        "tag": "Bouncie-origin · TL adopts",
        "inBouncie": "yes",
        "inTracklynk": "no",
        "scope": "v1",
        "tlEvidence": "",
        "tlNote": "only a coming-soon integrations label"
      }
    ]
  },
  {
    "category": "Alerts & Notifications",
    "rows": [
      {
        "feature": "Push Notifications (iOS & Android)",
        "segment": "B2C/B2B",
        "bouncie": "Yes. Documented reliability issues - multiple reports of push stopping, requiring app reset.",
        "tracklynk": "Yes. Reliable push with deep-link to relevant screen. Badge count for unread alerts.",
        "status": "issues",
        "statusLabel": "Issues",
        "tag": "Shared",
        "inBouncie": "yes",
        "inTracklynk": "yes",
        "scope": "v1",
        "tlEvidence": "services/pushNotifications.ts",
        "tlNote": "push subscribe via service worker"
      },
      {
        "feature": "SMS Text Alerts",
        "segment": "B2C/B2B",
        "bouncie": "Yes. Crash detection auto-SMS + optional SMS for driving alerts.",
        "tracklynk": "Yes. Configurable SMS for all alert types. Up to 5 emergency contacts.",
        "status": "working",
        "statusLabel": "Working",
        "tag": "Shared",
        "inBouncie": "yes",
        "inTracklynk": "partial",
        "scope": "v1",
        "tlEvidence": "pages/settings/safety/impact/index.tsx",
        "tlNote": "SMS toggles in UI, no real sending"
      },
      {
        "feature": "Email Alerts",
        "segment": "B2C/B2B",
        "bouncie": "Yes. Optional, configurable per event type.",
        "tracklynk": "Yes. Optional, with daily/weekly digest option.",
        "status": "working",
        "statusLabel": "Working",
        "tag": "Shared",
        "inBouncie": "yes",
        "inTracklynk": "partial",
        "scope": "v1",
        "tlEvidence": "pages/settings/alerts/ConfigSheets.tsx",
        "tlNote": "email channel toggle in alert config"
      },
      {
        "feature": "Geofence Entry / Exit Alerts",
        "segment": "B2C/B2B",
        "bouncie": "Yes. Independent entry/exit toggle per zone.",
        "tracklynk": "Yes. Per-zone toggle + custom alert mode (push, SMS, or silent log) per zone.",
        "status": "working",
        "statusLabel": "Working",
        "tag": "Shared",
        "inBouncie": "yes",
        "inTracklynk": "yes",
        "scope": "v1",
        "tlEvidence": "pages/settings/alerts/geo-zone/index.tsx",
        "tlNote": "geo-fence entry/exit alert config"
      },
      {
        "feature": "Speed Threshold Alerts",
        "segment": "B2C/B2B",
        "bouncie": "Yes. Posted speed limit data from Google Maps + custom fixed thresholds.",
        "tracklynk": "Yes. Posted limits + custom per-geofence thresholds.",
        "status": "working",
        "statusLabel": "Working",
        "tag": "Shared",
        "inBouncie": "yes",
        "inTracklynk": "yes",
        "scope": "v1",
        "tlEvidence": "pages/settings/alerts/index.tsx",
        "tlNote": "speed alert entry (GPS-based)"
      },
      {
        "feature": "Engine On / Off Alerts",
        "segment": "B2C/B2B",
        "bouncie": "Yes. Alerts on vehicle start and stop events.",
        "tracklynk": "Yes. Start/stop alerts with configurable quiet hours.",
        "status": "working",
        "statusLabel": "Working",
        "tag": "Shared",
        "inBouncie": "yes",
        "inTracklynk": "yes",
        "scope": "v1",
        "tlEvidence": "pages/settings/alerts/index.tsx",
        "tlNote": "trip-start/trip-end notifications"
      },
      {
        "feature": "Maintenance Due Reminders",
        "segment": "B2C/B2B",
        "bouncie": "Yes. Full Care Plan scheduler with custom task creation.",
        "tracklynk": "Yes. Custom task creation with flexible mileage/date triggers.",
        "status": "working",
        "statusLabel": "Working",
        "tag": "Bouncie strength",
        "inBouncie": "yes",
        "inTracklynk": "yes",
        "scope": "v1",
        "tlEvidence": "pages/settings/alerts/index.tsx",
        "tlNote": "maintenance reminder alert config"
      },
      {
        "feature": "Recall Alert Notifications",
        "segment": "B2C",
        "bouncie": "Not supported.",
        "tracklynk": "Yes. Push alert on new NHTSA recall with direct service scheduling link.",
        "status": "working",
        "statusLabel": "Working",
        "tag": "TL adds (Bouncie gap)",
        "inBouncie": "no",
        "inTracklynk": "yes",
        "scope": "v1",
        "tlEvidence": "pages/settings/alerts/index.tsx",
        "tlNote": "recalls alert entry"
      },
      {
        "feature": "Severe Weather Notifications",
        "segment": "B2C",
        "bouncie": "Yes. NWS advisory near vehicle location with push notification.",
        "tracklynk": "Yes. NWS + custom weather-trigger alerts filterable by severity level.",
        "status": "working",
        "statusLabel": "Working",
        "tag": "Bouncie-origin · TL adopts",
        "inBouncie": "yes",
        "inTracklynk": "yes",
        "scope": "v1",
        "tlEvidence": "pages/settings/alerts/ConfigSheets.tsx",
        "tlNote": "weather alert config with severity"
      },
      {
        "feature": "Low Fuel Warning",
        "segment": "B2C/B2B",
        "bouncie": "Yes. Alert when fuel drops below threshold (compatible vehicles).",
        "tracklynk": "Yes. Configurable fuel threshold alerts + weekly fuel trend summary.",
        "status": "working",
        "statusLabel": "Working",
        "tag": "Shared",
        "inBouncie": "yes",
        "inTracklynk": "yes",
        "scope": "v1",
        "tlEvidence": "pages/settings/alerts/index.tsx",
        "tlNote": "low fuel threshold alert"
      },
      {
        "feature": "In-App Rating Prompts (UX Issue)",
        "segment": "B2C/B2B",
        "bouncie": "Minimal - not a significant user complaint.",
        "tracklynk": "None. No in-app rating prompts.",
        "status": "issues",
        "statusLabel": "Issues",
        "tag": "TL avoids issue",
        "inBouncie": "partial",
        "inTracklynk": "no",
        "scope": "other",
        "tlEvidence": "",
        "tlNote": "app-store meta, not a built feature"
      }
    ]
  },
  {
    "category": "Mobile App & UX",
    "rows": [
      {
        "feature": "iOS App Rating & Adoption",
        "segment": "B2C/B2B",
        "bouncie": "4.8★ / 5,900+ ratings (id1211282909). Highest-rated OBD tracker on App Store. 84.7 MB.",
        "tracklynk": "Target: 4.5★+. Designed for consumer clarity with professional depth.",
        "status": "working",
        "statusLabel": "Working",
        "tag": "Bouncie strength",
        "inBouncie": "yes",
        "inTracklynk": "no",
        "scope": "other",
        "tlEvidence": "",
        "tlNote": "app-store metric, not code"
      },
      {
        "feature": "Android App Rating & Reviews",
        "segment": "B2C/B2B",
        "bouncie": "4.2★ / 1,660+ reviews (com.taillight.bouncie).",
        "tracklynk": "Target: 4.3★+. Material Design 3 compliant.",
        "status": "issues",
        "statusLabel": "Issues",
        "tag": "Bouncie strength",
        "inBouncie": "yes",
        "inTracklynk": "no",
        "scope": "other",
        "tlEvidence": "",
        "tlNote": "app-store metric, not code"
      },
      {
        "feature": "Home Screen Design",
        "segment": "B2C/B2B",
        "bouncie": "Full-screen live map - no widgets, no panels. Map IS the home screen.",
        "tracklynk": "Full-screen map as primary view with collapsible data drawer for secondary metrics.",
        "status": "working",
        "statusLabel": "Working",
        "tag": "Differentiator",
        "inBouncie": "yes",
        "inTracklynk": "yes",
        "scope": "other",
        "tlEvidence": "pages/home/index.tsx",
        "tlNote": "full home/map dashboard screen"
      },
      {
        "feature": "In-App Customer Support",
        "segment": "B2C/B2B",
        "bouncie": "Yes. Chat at chat.bouncie.com accessible from app. Well-reviewed.",
        "tracklynk": "Yes. In-app chat + knowledge base + ticket tracking.",
        "status": "issues",
        "statusLabel": "Issues",
        "tag": "Bouncie-only",
        "inBouncie": "yes",
        "inTracklynk": "yes",
        "scope": "other",
        "tlEvidence": "pages/settings/support/index.tsx",
        "tlNote": "FAQ and contact support screen"
      },
      {
        "feature": "Device Setup / Onboarding",
        "segment": "B2C/B2B",
        "bouncie": "~15 minutes from unboxing to tracking. No activation fee.",
        "tracklynk": "~10 minutes. No activation fee. Guided in-app walkthrough with video.",
        "status": "working",
        "statusLabel": "Working",
        "tag": "Shared",
        "inBouncie": "yes",
        "inTracklynk": "yes",
        "scope": "other",
        "tlEvidence": "pages/onboarding/device-setup-wizard/index.tsx",
        "tlNote": "multi-step onboarding/pairing flow"
      },
      {
        "feature": "Smartwatch Support",
        "segment": "B2C",
        "bouncie": "Not supported.",
        "tracklynk": "Not supported. (Planned for future release.)",
        "status": "working",
        "statusLabel": "Working",
        "tag": "TL adds (Bouncie gap)",
        "inBouncie": "no",
        "inTracklynk": "no",
        "scope": "other",
        "tlEvidence": "",
        "tlNote": "no smartwatch UI or integration"
      },
      {
        "feature": "Multiple Vehicle Switcher",
        "segment": "B2C/B2B",
        "bouncie": "Map dropdown at top of screen for quick switching.",
        "tracklynk": "Map dropdown + swipe gesture between vehicles.",
        "status": "working",
        "statusLabel": "Working",
        "tag": "Shared",
        "inBouncie": "yes",
        "inTracklynk": "yes",
        "scope": "other",
        "tlEvidence": "pages/home/index.tsx",
        "tlNote": "vehicle switcher sheet on home"
      },
      {
        "feature": "Amazon Alexa Integration",
        "segment": "B2C",
        "bouncie": "Yes. Direct integration for location queries. Occasional glitches noted.",
        "tracklynk": "Yes. Direct integration for location + status queries.",
        "status": "working",
        "statusLabel": "Working",
        "tag": "Shared",
        "inBouncie": "yes",
        "inTracklynk": "no",
        "scope": "other",
        "tlEvidence": "",
        "tlNote": "no Alexa integration in frontend"
      },
      {
        "feature": "App Update Frequency",
        "segment": "B2C/B2B",
        "bouncie": "Extremely active: v4.17.6 through v4.19.3 within 6 weeks (Feb–Mar 2026). Multiple releases/month.",
        "tracklynk": "Bi-weekly release cadence. Rapid iteration on user feedback.",
        "status": "working",
        "statusLabel": "Working",
        "tag": "Bouncie strength",
        "inBouncie": "yes",
        "inTracklynk": "no",
        "scope": "other",
        "tlEvidence": "",
        "tlNote": "release-cadence meta, not code"
      },
      {
        "feature": "Dark / Light Mode Toggle",
        "segment": "B2C",
        "bouncie": "System default only - no independent toggle.",
        "tracklynk": "Independent dark/light mode toggle. Defaults to system but allows override.",
        "status": "conditional",
        "statusLabel": "Conditional",
        "tag": "TL exceeds Bouncie",
        "inBouncie": "partial",
        "inTracklynk": "no",
        "scope": "other",
        "tlEvidence": "",
        "tlNote": "theme hardcoded dark, no toggle"
      }
    ]
  },
  {
    "category": "Integrations, API & Ecosystem",
    "rows": [
      {
        "feature": "Public REST API",
        "segment": "B2B",
        "bouncie": "Yes. Fully documented at docs.bouncie.dev with OAuth 2.0. Third-party Ruby clients on GitHub.",
        "tracklynk": "Yes. Open REST API with OAuth 2.0. Public documentation. No enterprise approval gate.",
        "status": "working",
        "statusLabel": "Working",
        "tag": "Bouncie-origin · TL adopts",
        "inBouncie": "yes",
        "inTracklynk": "no",
        "scope": "v1",
        "tlEvidence": "",
        "tlNote": "no API surface in frontend"
      },
      {
        "feature": "Webhooks",
        "segment": "B2B",
        "bouncie": "Yes. Exponential backoff retry for reliable event delivery.",
        "tracklynk": "Yes. Webhooks with configurable retry logic.",
        "status": "working",
        "statusLabel": "Working",
        "tag": "Bouncie-origin · TL adopts",
        "inBouncie": "yes",
        "inTracklynk": "no",
        "scope": "v1",
        "tlEvidence": "",
        "tlNote": "only a coming-soon integrations label"
      },
      {
        "feature": "Zapier Integration",
        "segment": "B2B",
        "bouncie": "Yes. Official integration connecting to 6,000+ apps (Google Sheets, Slack, Notion, Salesforce).",
        "tracklynk": "Yes. Pre-built Zapier integration. Fleet operators auto-log trips to spreadsheets.",
        "status": "working",
        "statusLabel": "Working",
        "tag": "Bouncie-origin · TL adopts",
        "inBouncie": "yes",
        "inTracklynk": "no",
        "scope": "v1",
        "tlEvidence": "",
        "tlNote": "label only, no integration"
      },
      {
        "feature": "IFTTT Integration",
        "segment": "B2C",
        "bouncie": "Yes. Official channel at ifttt.com/bouncie. Smart home triggers.",
        "tracklynk": "Not supported. (Zapier covers most automation use cases.)",
        "status": "working",
        "statusLabel": "Working",
        "tag": "Bouncie-only",
        "inBouncie": "yes",
        "inTracklynk": "no",
        "scope": "other",
        "tlEvidence": "",
        "tlNote": "no IFTTT integration"
      },
      {
        "feature": "Google Assistant",
        "segment": "B2C",
        "bouncie": "Yes. Voice queries for vehicle location and status.",
        "tracklynk": "Yes. Voice queries for location, status, and trip summaries.",
        "status": "working",
        "statusLabel": "Working",
        "tag": "Bouncie-origin · TL adopts",
        "inBouncie": "yes",
        "inTracklynk": "no",
        "scope": "other",
        "tlEvidence": "",
        "tlNote": "no Google Assistant integration"
      },
      {
        "feature": "Home Assistant Integration",
        "segment": "B2B",
        "bouncie": "Yes. Community-built at GitHub: mandarons/ha-bouncie. Uses public API.",
        "tracklynk": "Planned. API-first architecture enables future community integrations.",
        "status": "working",
        "statusLabel": "Working",
        "tag": "Bouncie-only",
        "inBouncie": "yes",
        "inTracklynk": "no",
        "scope": "other",
        "tlEvidence": "",
        "tlNote": "no Home Assistant integration"
      },
      {
        "feature": "Amazon Alexa",
        "segment": "B2C/B2B",
        "bouncie": "Yes. Direct integration for location queries.",
        "tracklynk": "Yes. Direct integration for location + status.",
        "status": "working",
        "statusLabel": "Working",
        "tag": "Shared",
        "inBouncie": "yes",
        "inTracklynk": "no",
        "scope": "other",
        "tlEvidence": "",
        "tlNote": "no Alexa integration"
      },
      {
        "feature": "GasBuddy GasBack Rewards",
        "segment": "B2C",
        "bouncie": "Not supported.",
        "tracklynk": "Not supported.",
        "status": "working",
        "statusLabel": "Working",
        "tag": "TL adds (Bouncie gap)",
        "inBouncie": "no",
        "inTracklynk": "no",
        "scope": "other",
        "tlEvidence": "",
        "tlNote": "no GasBuddy integration"
      },
      {
        "feature": "VyncsMiles Companion App",
        "segment": "B2C",
        "bouncie": "Not supported.",
        "tracklynk": "Not supported. (Mileage tracking built into primary app.)",
        "status": "working",
        "statusLabel": "Working",
        "tag": "TL adds (Bouncie gap)",
        "inBouncie": "no",
        "inTracklynk": "no",
        "scope": "other",
        "tlEvidence": "",
        "tlNote": "competitor app, not present"
      },
      {
        "feature": "Vyncs Groups (Family Phone Tracking)",
        "segment": "B2C",
        "bouncie": "Not supported.",
        "tracklynk": "Not supported. (Privacy-first: vehicles only, no phone tracking.)",
        "status": "working",
        "statusLabel": "Working",
        "tag": "TL adds (Bouncie gap)",
        "inBouncie": "no",
        "inTracklynk": "no",
        "scope": "other",
        "tlEvidence": "",
        "tlNote": "no phone-tracking groups feature"
      },
      {
        "feature": "Real-Time Traffic Overlay",
        "segment": "B2C/B2B",
        "bouncie": "Yes. Added v4.14+. Google Maps traffic layer.",
        "tracklynk": "Yes. Google Maps traffic layer included.",
        "status": "working",
        "statusLabel": "Working",
        "tag": "Shared",
        "inBouncie": "yes",
        "inTracklynk": "yes",
        "scope": "other",
        "tlEvidence": "pages/home/index.tsx",
        "tlNote": "Google TrafficLayer toggle"
      }
    ]
  },
  {
    "category": "Hardware Device",
    "rows": [
      {
        "feature": "Form Factor",
        "segment": "B2C/B2B",
        "bouncie": "OBD-II dongle - \"smallest cellular OBD device anywhere\" (~1.875\" × 1.75\"). Under 3 oz.",
        "tracklynk": "OBD-II dongle. Compact form factor under 3 oz. Low-profile design for concealment.",
        "status": "working",
        "statusLabel": "Working",
        "tag": "Shared",
        "inBouncie": "yes",
        "inTracklynk": "no",
        "scope": "other",
        "tlEvidence": "",
        "tlNote": "physical hardware, not coded"
      },
      {
        "feature": "Cellular Network Technology",
        "segment": "B2C/B2B",
        "bouncie": "4G LTE-M (IoT-optimized). Lower power consumption, better building/garage penetration.",
        "tracklynk": "4G LTE-M (IoT-optimized). Multi-carrier: AT&T, T-Mobile, Verizon fallback.",
        "status": "working",
        "statusLabel": "Working",
        "tag": "Bouncie strength",
        "inBouncie": "yes",
        "inTracklynk": "no",
        "scope": "other",
        "tlEvidence": "",
        "tlNote": "physical hardware, not coded"
      },
      {
        "feature": "Power Source",
        "segment": "B2C/B2B",
        "bouncie": "OBD port (vehicle 12V power). No battery. Never needs charging.",
        "tracklynk": "OBD port (vehicle 12V power). No battery. Sleep mode optimization for minimal drain.",
        "status": "working",
        "statusLabel": "Working",
        "tag": "Shared",
        "inBouncie": "yes",
        "inTracklynk": "no",
        "scope": "other",
        "tlEvidence": "",
        "tlNote": "physical hardware, not coded"
      },
      {
        "feature": "GPS + Accelerometer Sensors",
        "segment": "B2C/B2B",
        "bouncie": "GPS + 3-axis accelerometer. All data processed in cloud.",
        "tracklynk": "GPS + 3-axis accelerometer. Hybrid edge/cloud processing.",
        "status": "working",
        "statusLabel": "Working",
        "tag": "TL exceeds Bouncie",
        "inBouncie": "yes",
        "inTracklynk": "no",
        "scope": "other",
        "tlEvidence": "",
        "tlNote": "physical hardware, not coded"
      },
      {
        "feature": "Embedded SIM",
        "segment": "B2C/B2B",
        "bouncie": "US/Canada/Mexico networks (AT&T + T-Mobile).",
        "tracklynk": "US/Canada/Mexico (AT&T, T-Mobile, Verizon fallback).",
        "status": "working",
        "statusLabel": "Working",
        "tag": "TL exceeds Bouncie",
        "inBouncie": "yes",
        "inTracklynk": "no",
        "scope": "other",
        "tlEvidence": "",
        "tlNote": "physical hardware, not coded"
      },
      {
        "feature": "On-Device Edge Computing",
        "segment": "B2C/B2B",
        "bouncie": "No. Cloud-first architecture - all processing in cloud.",
        "tracklynk": "Selective edge processing for latency-sensitive events (crash, tamper). Cloud for analytics.",
        "status": "working",
        "statusLabel": "Working",
        "tag": "TL adds (Bouncie gap)",
        "inBouncie": "no",
        "inTracklynk": "no",
        "scope": "other",
        "tlEvidence": "",
        "tlNote": "physical hardware, not coded"
      },
      {
        "feature": "LED Status Indicator",
        "segment": "B2C",
        "bouncie": "Green LED - always on/flashing. Users complain about visibility.",
        "tracklynk": "Configurable LED: on/off/dim modes. User can disable via app settings.",
        "status": "issues",
        "statusLabel": "Issues",
        "tag": "Shared",
        "inBouncie": "yes",
        "inTracklynk": "partial",
        "scope": "other",
        "tlEvidence": "pages/settings/devices/index.tsx",
        "tlNote": "device status screen, no LED reference"
      },
      {
        "feature": "Device Visibility / Concealment",
        "segment": "B2C",
        "bouncie": "Visible under dashboard. Varies by vehicle model.",
        "tracklynk": "Low-profile design. Installation guide with concealment tips per vehicle type.",
        "status": "issues",
        "statusLabel": "Issues",
        "tag": "Shared",
        "inBouncie": "yes",
        "inTracklynk": "no",
        "scope": "other",
        "tlEvidence": "",
        "tlNote": "physical install attribute, not coded"
      },
      {
        "feature": "Network Transition Handling",
        "segment": "B2C/B2B",
        "bouncie": "Replacement required - NO trade-in. 3G shutdown bricked devices, generating lasting negative sentiment.",
        "tracklynk": "Free replacement included. Future-proofed with multi-band LTE-M modem.",
        "status": "issues",
        "statusLabel": "Issues",
        "tag": "TL exceeds Bouncie",
        "inBouncie": "partial",
        "inTracklynk": "no",
        "scope": "other",
        "tlEvidence": "",
        "tlNote": "hardware/connectivity, not coded"
      }
    ]
  },
  {
    "category": "Driving Behavior Intelligence (V2)",
    "rows": [
      {
        "feature": "Driver Progress Tracking & Coaching",
        "segment": "",
        "bouncie": "Not supported.",
        "tracklynk": "30-day rolling improvement score with trend analysis (e.g., 'Speeding down 40%'), weekly coaching, and milestone badges.",
        "status": "na",
        "statusLabel": "—",
        "tag": "V2 roadmap",
        "inBouncie": "no",
        "inTracklynk": "partial",
        "scope": "v2",
        "tlEvidence": "data/driverFactors.ts",
        "tlNote": "per-factor tips, no progress/coaching flow"
      },
      {
        "feature": "Distracted Driving Risk Score",
        "segment": "",
        "bouncie": "Not supported.",
        "tracklynk": "Camera-free distraction detection using GPS + accelerometer patterns (speed oscillations, delayed stops, lane variance) → Low/Med/High trip risk.",
        "status": "na",
        "statusLabel": "—",
        "tag": "V2 roadmap",
        "inBouncie": "no",
        "inTracklynk": "no",
        "scope": "v2",
        "tlEvidence": "",
        "tlNote": "no distracted-driving score"
      },
      {
        "feature": "Lane Change Frequency Profiling",
        "segment": "",
        "bouncie": "Not supported.",
        "tracklynk": "Profiles lane-change frequency from GPS + accelerometer signatures as a behavioural risk input.",
        "status": "na",
        "statusLabel": "—",
        "tag": "V2 roadmap",
        "inBouncie": "no",
        "inTracklynk": "no",
        "scope": "v2",
        "tlEvidence": "",
        "tlNote": "no lane-change profiling"
      },
      {
        "feature": "Route Familiarity Adjustment",
        "segment": "",
        "bouncie": "Not supported.",
        "tracklynk": "ML classifies routes as Familiar vs Unfamiliar and weights safety scoring accordingly, cutting false-positive fatigue.",
        "status": "na",
        "statusLabel": "—",
        "tag": "V2 roadmap",
        "inBouncie": "no",
        "inTracklynk": "no",
        "scope": "v2",
        "tlEvidence": "",
        "tlNote": "no route-familiarity logic"
      }
    ]
  },
  {
    "category": "Vehicle Health Intelligence (V2)",
    "rows": [
      {
        "feature": "Vehicle Health Report Card",
        "segment": "",
        "bouncie": "Not supported.",
        "tracklynk": "Quarterly health score (0–100) across 6 systems (Battery, Engine, Fuel, Cooling, Electrical, Emissions) with trends.",
        "status": "na",
        "statusLabel": "—",
        "tag": "V2 roadmap",
        "inBouncie": "no",
        "inTracklynk": "yes",
        "scope": "v2",
        "tlEvidence": "pages/vehicles/health/index.tsx",
        "tlNote": "composite health score report card"
      },
      {
        "feature": "Predictive Maintenance Alerts",
        "segment": "",
        "bouncie": "Not supported.",
        "tracklynk": "ML failure forecasts from OBD trends (voltage decay, temp drift, fuel-trim shifts) — flags issues weeks early with est. repair cost.",
        "status": "na",
        "statusLabel": "—",
        "tag": "V2 roadmap",
        "inBouncie": "no",
        "inTracklynk": "partial",
        "scope": "v2",
        "tlEvidence": "pages/vehicles/health/maintenance/index.tsx",
        "tlNote": "due-date reminders, not predictive"
      },
      {
        "feature": "Service History Blockchain",
        "segment": "",
        "bouncie": "Not supported.",
        "tracklynk": "Immutable, timestamped maintenance log with QR code + Carfax/AutoCheck integration to boost resale value.",
        "status": "na",
        "statusLabel": "—",
        "tag": "V2 roadmap",
        "inBouncie": "no",
        "inTracklynk": "no",
        "scope": "v2",
        "tlEvidence": "",
        "tlNote": "no blockchain service history"
      }
    ]
  },
  {
    "category": "Advanced Behavioral Insights (V2)",
    "rows": [
      {
        "feature": "Driver Personality Profiling",
        "segment": "",
        "bouncie": "Not supported.",
        "tracklynk": "ML driver archetypes (e.g., 'Highway Cruiser') across Aggressiveness, Consistency, Efficiency, Risk Tolerance.",
        "status": "na",
        "statusLabel": "—",
        "tag": "V2 roadmap",
        "inBouncie": "no",
        "inTracklynk": "no",
        "scope": "v2",
        "tlEvidence": "",
        "tlNote": "no personality profiling"
      },
      {
        "feature": "Peer Comparison Benchmarking",
        "segment": "",
        "bouncie": "Not supported.",
        "tracklynk": "Anonymous percentile ranking vs similar drivers (age, vehicle, region) with monthly progress updates.",
        "status": "na",
        "statusLabel": "—",
        "tag": "V2 roadmap",
        "inBouncie": "no",
        "inTracklynk": "partial",
        "scope": "v2",
        "tlEvidence": "pages/health/index.tsx",
        "tlNote": "percentile/leaderboard, no peer benchmark page"
      }
    ]
  },
  {
    "category": "Financial Intelligence (V2)",
    "rows": [
      {
        "feature": "True Cost of Ownership Dashboard",
        "segment": "",
        "bouncie": "Not supported.",
        "tracklynk": "Per-vehicle total cost tracking (fuel, maintenance, insurance, depreciation, idle waste) with fleet rankings.",
        "status": "na",
        "statusLabel": "—",
        "tag": "V2 roadmap",
        "inBouncie": "no",
        "inTracklynk": "no",
        "scope": "v2",
        "tlEvidence": "",
        "tlNote": "no cost-of-ownership dashboard"
      },
      {
        "feature": "Trip Purpose & Business Mileage Automation",
        "segment": "",
        "bouncie": "Not supported.",
        "tracklynk": "Auto-tagged trip categorization (Business/Personal/Commute) with IRS-compliant mileage exports and deduction summaries.",
        "status": "na",
        "statusLabel": "—",
        "tag": "V2 roadmap",
        "inBouncie": "no",
        "inTracklynk": "yes",
        "scope": "v2",
        "tlEvidence": "pages/trips/categorize/index.tsx",
        "tlNote": "trip category/purpose with IRS mileage"
      },
      {
        "feature": "Vehicle Utilization Analysis",
        "segment": "",
        "bouncie": "Not supported.",
        "tracklynk": "Per-vehicle utilization metrics (miles/month, days parked, sitting cost) with downsizing recommendations.",
        "status": "na",
        "statusLabel": "—",
        "tag": "V2 roadmap",
        "inBouncie": "no",
        "inTracklynk": "no",
        "scope": "v2",
        "tlEvidence": "",
        "tlNote": "no utilization analysis screen"
      }
    ]
  },
  {
    "category": "Insurance & Compliance (V2)",
    "rows": [
      {
        "feature": "Insurance Telematics Report Generator",
        "segment": "",
        "bouncie": "Not supported.",
        "tracklynk": "90-day standardized telematics report with insurer-ready templates and predicted UBI discount (12–18%).",
        "status": "na",
        "statusLabel": "—",
        "tag": "V2 roadmap",
        "inBouncie": "no",
        "inTracklynk": "yes",
        "scope": "v2",
        "tlEvidence": "pages/settings/insurance/score-card/index.tsx",
        "tlNote": "insurance score card and methodology"
      },
      {
        "feature": "Crash Documentation Automation",
        "segment": "",
        "bouncie": "Not supported.",
        "tracklynk": "Auto-generated crash report on impact (GPS, pre-crash speed, G-force, weather) exportable as one-tap PDF.",
        "status": "na",
        "statusLabel": "—",
        "tag": "V2 roadmap",
        "inBouncie": "no",
        "inTracklynk": "partial",
        "scope": "v2",
        "tlEvidence": "data/safety.ts",
        "tlNote": "impact events stored, no crash report doc"
      }
    ]
  },
  {
    "category": "Eco-Driving & Efficiency (V2)",
    "rows": [
      {
        "feature": "Eco-Driving Score & Coaching",
        "segment": "",
        "bouncie": "Not supported.",
        "tracklynk": "Eco-score (0–100) on throttle, coasting, and shift habits with per-trip savings and gamified badges.",
        "status": "na",
        "statusLabel": "—",
        "tag": "V2 roadmap",
        "inBouncie": "no",
        "inTracklynk": "no",
        "scope": "v2",
        "tlEvidence": "",
        "tlNote": "no eco-driving score/coaching"
      },
      {
        "feature": "Carbon Footprint Tracking",
        "segment": "",
        "bouncie": "Not supported.",
        "tracklynk": "Monthly CO2 calculation from fuel use (EPA factors) with peer comparisons and offset recommendations; ESG reporting.",
        "status": "na",
        "statusLabel": "—",
        "tag": "V2 roadmap",
        "inBouncie": "no",
        "inTracklynk": "no",
        "scope": "v2",
        "tlEvidence": "",
        "tlNote": "no carbon footprint tracking"
      }
    ]
  }
]

export default COMPARISON
